on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Download network
        run: python3 download_net.py
      - name: Run Clippy
        run: RUSTFLAGS="-Ctarget-cpu=native" cargo clippy --all-targets --all-features
